baseURL = '/'
languageCode = 'en-us'
title = 'The Sunday Blender'
theme = "pehtheme-hugo"

[permalinks]
	posts = "/p/:slug/"

[params]
	description = 'The Sunday Blender - A minimalist blog built with Hugo and Pehtheme'
	mainSections = 'posts'

[author]
	name = 'Clayton Man'
	bio = 'A newsman making the best news for kids'

[build]
	writeStats = true

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
