baseURL = '/'
languageCode = 'en-us'
title = 'The Sunday Blender'
theme = "diary"

[permalinks]
	posts = "/p/:slug/"

[params]
	subtitle = "Making news interesting for kids"
	description = 'The Sunday Blender - A minimalist blog built with Hugo and Diary theme'
	enableOpenGraph = true
	enableTwitterCards = true
	author = "Clayton Man"
	author_bio = "A newsman making the best news for kids"

[build]
	writeStats = true

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
